language: ruby
rvm:
  - 2.2.0
env:
  - DB=sqlite
services:
  - elasticsearch
before_script:
  - sleep 10
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - RAILS_ENV=test bundle exec rake